export interface SpellingEntry {
  /** Difficulty band 1–6, mapped from zone number (matches the comprehension bank). */
  zone: 1 | 2 | 3 | 4 | 5 | 6
  /** The word to spell — lowercase a–z only (tiles are one letter each). */
  word: string
  /** Read aloud by the "in a sentence" button. Gives context without spelling it out. */
  sentence: string
  /** Shown on the 3rd wrong attempt (§10) — a phonics nudge, never the full word. */
  hint: string
}

// Static spelling bank: 25 words per zone (150 total), themed to that zone's region.
//
// GRADE CALIBRATION — the ramp tops out at solid 4th grade, and every word is one
// a 9-year-old already knows how to SAY. Difficulty comes from the spelling
// pattern, not from vocabulary she has never met:
//
//   Band 1 (Z1) ~grade 1   | 4–6 letters, short vowels, CVCe, simple digraphs
//   Band 2 (Z2) ~grade 2   | 5–7 letters, blends, double consonants
//   Band 3 (Z3) ~grade 2–3 | 5–8 letters, vowel teams (ea/oa/ai), r-controlled
//   Band 4 (Z4) ~grade 3   | 5–9 letters, compound words, -ing/-ed suffix rules
//   Band 5 (Z5) ~grade 3–4 | 6–10 letters, silent letters, common suffixes
//   Band 6 (Z6) ~grade 4   | 8–11 letters, multisyllable, -ful/-ness/-ous/-ship
//
// Deliberately NOT here: turbulent, atmosphere, celestial, brilliance,
// constellation. All 5th–6th grade vocabulary — long words she would be decoding
// rather than spelling. Length alone is not difficulty: "beautiful" and
// "turbulent" are both 9 letters, but only one of them is a word she owns.
//
// Anti-repeat cycling in spellingGenerator.ts means a band's 25 words cycle
// before any repeats.
export const SPELLING_BANK: SpellingEntry[] = [
  // ══ Zone 1 — Starter: Brindlewood Home, Sunflower Hollow, Proving Glade ══
  // Band 1 ~grade 1: short vowels, CVCe, simple digraphs.
  { zone: 1, word: 'pony',
    sentence: 'Every pony in the glade wants to be her friend.',
    hint: "Starts with 'p'. The 'y' at the end sounds like 'ee'." },
  { zone: 1, word: 'mane',
    sentence: 'Her mane shines in the morning sun.',
    hint: "Starts with 'm'. The silent 'e' at the end makes the 'a' say its name." },
  { zone: 1, word: 'hoof',
    sentence: 'The pony tapped one hoof on the path.',
    hint: "Starts with 'h'. Two 'o' letters in the middle make the 'oo' sound." },
  { zone: 1, word: 'tail',
    sentence: 'She swished her tail at a buzzing bee.',
    hint: "Starts with 't'. The 'ai' in the middle says 'ay'." },
  { zone: 1, word: 'star',
    sentence: 'The first star appeared above the glade.',
    hint: "Begins with an 'st' blend and finishes with 'ar'." },
  { zone: 1, word: 'leaf',
    sentence: 'A green leaf floated down from the tree.',
    hint: "Starts with 'l'. The 'ea' in the middle says 'ee'." },
  { zone: 1, word: 'glow',
    sentence: 'Her horn began to glow with soft light.',
    hint: "Begins with a 'gl' blend and ends with 'ow', like in 'snow'." },
  { zone: 1, word: 'wish',
    sentence: 'She made a wish before the race began.',
    hint: "Starts with 'w' and ends with the 'sh' sound — two letters, one sound." },
  { zone: 1, word: 'gate',
    sentence: 'The wooden gate creaked when it opened.',
    hint: "Starts with 'g'. The silent 'e' makes the 'a' say its name." },
  { zone: 1, word: 'home',
    sentence: 'Brindlewood Home is where her journey starts.',
    hint: "Starts with 'h'. The silent 'e' makes the 'o' say its name." },
  { zone: 1, word: 'path',
    sentence: 'A narrow path led into the hollow.',
    hint: "Starts with 'p' and ends with the 'th' sound." },
  { zone: 1, word: 'seed',
    sentence: 'She planted a sunflower seed in the soil.',
    hint: "Starts with 's'. Two 'e' letters in the middle say 'ee'." },
  { zone: 1, word: 'nest',
    sentence: 'A tiny bird built a nest in the hedge.',
    hint: "Begins with an 'n' and ends with an 'st' blend." },
  { zone: 1, word: 'wing',
    sentence: 'The bird stretched out one wing.',
    hint: "Starts with 'w'. It ends with 'ng', the sound at the end of 'sing'." },
  { zone: 1, word: 'pond',
    sentence: 'Ducks paddled across the little pond.',
    hint: "Starts with 'p' and ends with an 'nd' blend." },
  { zone: 1, word: 'barn',
    sentence: 'The ponies sleep in a warm barn.',
    hint: "Starts with 'b'. The middle is 'ar', like in 'car'." },
  { zone: 1, word: 'hill',
    sentence: 'They galloped up the grassy hill.',
    hint: "Starts with 'h' and ends with a double 'l'." },
  { zone: 1, word: 'rock',
    sentence: 'A flat rock makes a good place to rest.',
    hint: "Starts with 'r'. The 'ck' at the end is two letters for one sound." },
  { zone: 1, word: 'bloom',
    sentence: 'The sunflowers bloom all summer long.',
    hint: "Begins with a 'bl' blend. The 'oo' sounds like in 'moon'." },
  { zone: 1, word: 'grass',
    sentence: 'The tall grass tickled her legs.',
    hint: "Begins with a 'gr' blend and ends with a double 's'." },
  { zone: 1, word: 'petal',
    sentence: 'One yellow petal drifted to the ground.',
    hint: "Starts with 'pet'. It ends with 'al', not 'el'." },
  { zone: 1, word: 'field',
    sentence: 'They galloped across the open field.',
    hint: "Starts with 'f'. Remember: 'i' before 'e' here." },
  { zone: 1, word: 'cloud',
    sentence: 'One fluffy cloud drifted over the glade.',
    hint: "Begins with a 'cl' blend. The 'ou' says 'ow', like in 'out'." },
  { zone: 1, word: 'happy',
    sentence: 'She felt happy after winning her first match.',
    hint: "Starts with 'ha'. Double 'p' in the middle, and a 'y' that says 'ee'." },
  { zone: 1, word: 'friend',
    sentence: 'Every pony she meets becomes a friend.',
    hint: "Begins with an 'fr' blend. There is a hidden 'i' — think 'fri-end'." },

  // ══ Zone 2 — Earth: Pebblebrook, Mossgrove, Granite Hall ═════════════════
  // Band 2 ~grade 2: blends, digraphs, double consonants.
  { zone: 2, word: 'stone',
    sentence: 'A smooth grey stone sat beside the brook.',
    hint: "Begins with an 'st' blend. The silent 'e' makes the 'o' say its name." },
  { zone: 2, word: 'brook',
    sentence: 'Pebblebrook is named for its bubbling brook.',
    hint: "Begins with a 'br' blend. The 'oo' sounds like in 'book'." },
  { zone: 2, word: 'acorn',
    sentence: 'An acorn fell from the oak branch.',
    hint: "Starts with the letter 'a' all by itself, then 'corn'." },
  { zone: 2, word: 'trail',
    sentence: 'A muddy trail wound through the trees.',
    hint: "Begins with a 'tr' blend. The 'ai' in the middle says 'ay'." },
  { zone: 2, word: 'roots',
    sentence: 'Thick roots twisted across the ground.',
    hint: "Starts with 'r'. Two 'o' letters say 'oo', and it ends with 's'." },
  { zone: 2, word: 'mossy',
    sentence: 'The mossy log was soft and green.',
    hint: "Starts with 'mo'. Double 's' in the middle, and a 'y' that says 'ee'." },
  { zone: 2, word: 'shade',
    sentence: 'They rested in the cool shade of an oak.',
    hint: "Begins with the 'sh' sound. The silent 'e' makes the 'a' say its name." },
  { zone: 2, word: 'berry',
    sentence: 'She found one ripe berry on the bush.',
    hint: "Starts with 'be'. Double 'r' in the middle, and a 'y' that says 'ee'." },
  { zone: 2, word: 'muddy',
    sentence: 'Her hooves were muddy after the rain.',
    hint: "Starts with 'mu'. Double 'd' in the middle, and a 'y' that says 'ee'." },
  { zone: 2, word: 'green',
    sentence: 'Everything in Mossgrove is deep green.',
    hint: "Begins with a 'gr' blend. Two 'e' letters in the middle say 'ee'." },
  { zone: 2, word: 'pebble',
    sentence: 'She nudged a tiny pebble with her hoof.',
    hint: "Starts with 'peb'. Double 'b' in the middle, and it ends in 'le'." },
  { zone: 2, word: 'forest',
    sentence: 'Mossgrove sits deep inside the forest.',
    hint: "Starts with 'for'. The ending sounds like the word 'rest'." },
  { zone: 2, word: 'branch',
    sentence: 'A thick branch hung over the trail.',
    hint: "Begins with a 'br' blend and ends with the 'ch' sound." },
  { zone: 2, word: 'garden',
    sentence: 'Her garden grows carrots and clover.',
    hint: "Starts with 'gar'. The ending is 'den', like a cozy little room." },
  { zone: 2, word: 'meadow',
    sentence: 'The ponies rested in a sunny meadow.',
    hint: "Starts with 'mea', where 'ea' says 'eh'. It ends with 'ow', like 'shadow'." },
  { zone: 2, word: 'sprout',
    sentence: 'A green sprout pushed up through the dirt.',
    hint: "Begins with a three-letter 'spr' blend. The 'ou' sounds like in 'shout'." },
  { zone: 2, word: 'hollow',
    sentence: 'They camped inside a hollow log.',
    hint: "Starts with 'hol' and has a double 'l'. It ends with 'ow'." },
  { zone: 2, word: 'tunnel',
    sentence: 'A narrow tunnel ran under the hill.',
    hint: "Starts with 'tun'. Double 'n' in the middle, and it ends with 'el'." },
  { zone: 2, word: 'valley',
    sentence: 'The whole valley was covered in clover.',
    hint: "Starts with 'val'. Double 'l' in the middle, and it ends with 'ey'." },
  { zone: 2, word: 'rabbit',
    sentence: 'A brown rabbit hopped across the path.',
    hint: "Starts with 'rab'. Double 'b' in the middle, and it ends with 'it'." },
  { zone: 2, word: 'summer',
    sentence: 'Mossgrove is warmest in the summer.',
    hint: "Starts with 'sum'. Double 'm' in the middle, and it ends with 'er'." },
  { zone: 2, word: 'blossom',
    sentence: 'Every blossom opened after the rain.',
    hint: "Begins with a 'bl' blend. There is a double 's' in the middle." },
  { zone: 2, word: 'boulder',
    sentence: 'A huge boulder blocked the mountain road.',
    hint: "Starts with 'boul' — there is a silent 'u' right after the 'o'." },
  { zone: 2, word: 'thicket',
    sentence: 'A rabbit darted into the thicket.',
    hint: "Begins with the 'th' sound. The middle is 'ck', and it ends with 'et'." },
  { zone: 2, word: 'granite',
    sentence: 'Granite Hall is carved from solid rock.',
    hint: "Starts with 'gran'. The silent 'e' at the end makes the 'i' say its name." },

  // ══ Zone 3 — Water: Saltspray Cove, Mistreef, Coral Sanctum ══════════════
  // Band 3 ~grade 2–3: vowel teams and r-controlled vowels.
  { zone: 3, word: 'ocean',
    sentence: 'The ocean stretched past the horizon.',
    hint: "Starts with 'oce' — that 'c' makes a 'sh' sound. It ends with 'an'." },
  { zone: 3, word: 'coral',
    sentence: 'The Coral Sanctum glitters pink and orange.',
    hint: "Starts with 'cor'. It ends with 'al', not 'el'." },
  { zone: 3, word: 'waves',
    sentence: 'Gentle waves rolled onto the sand.',
    hint: "Starts with 'wa'. There is a silent 'e' before the final 's'." },
  { zone: 3, word: 'beach',
    sentence: 'They trotted along the sandy beach.',
    hint: "Starts with 'b'. The 'ea' says 'ee', and it ends with the 'ch' sound." },
  { zone: 3, word: 'shore',
    sentence: 'A crab scuttled along the shore.',
    hint: "Begins with the 'sh' sound, then 'ore' like in 'more'." },
  { zone: 3, word: 'pearl',
    sentence: 'She found a shining pearl in the shallows.',
    hint: "Starts with 'pe'. The middle is 'ear', but it sounds like 'ur'." },
  { zone: 3, word: 'tides',
    sentence: 'The tides rise higher at Mistreef.',
    hint: "Starts with 't'. The silent 'e' makes the 'i' say its name." },
  { zone: 3, word: 'sandy',
    sentence: 'The sandy bottom sparkled in the sunlight.',
    hint: "Starts with 'sand', then a 'y' that says 'ee'." },
  { zone: 3, word: 'splash',
    sentence: 'She made a big splash in the shallow water.',
    hint: "Begins with a three-letter 'spl' blend and ends with 'sh'." },
  { zone: 3, word: 'ripple',
    sentence: 'One ripple spread across the still pool.',
    hint: "Starts with 'rip'. Double 'p' in the middle, and it ends in 'le'." },
  { zone: 3, word: 'lagoon',
    sentence: 'A warm lagoon sat behind the reef.',
    hint: "Starts with 'la'. The 'oo' in the second part sounds like 'moon'." },
  { zone: 3, word: 'bubble',
    sentence: 'A silver bubble rose to the surface.',
    hint: "Starts with 'bub'. Double 'b' in the middle, and it ends in 'le'." },
  { zone: 3, word: 'island',
    sentence: 'A tiny island poked out of the water.',
    hint: "Starts with 'is'. The 's' in the middle is silent — think 'eye-land'." },
  { zone: 3, word: 'turtle',
    sentence: 'A sea turtle glided past the coral.',
    hint: "Starts with 'tur'. The ending is 'tle', like in 'little'." },
  { zone: 3, word: 'anchor',
    sentence: 'An old anchor rested on the seabed.',
    hint: "Starts with 'an'. The 'ch' in the middle makes a 'k' sound." },
  { zone: 3, word: 'seaweed',
    sentence: 'Long strands of seaweed swayed below.',
    hint: "Two small words joined: 'sea' and 'weed'. One uses 'ea', the other 'ee'." },
  { zone: 3, word: 'shallow',
    sentence: 'The water is shallow near the rocks.',
    hint: "Begins with 'sh'. Double 'l' in the middle, and it ends with 'ow'." },
  { zone: 3, word: 'current',
    sentence: 'A strong current pulled them sideways.',
    hint: "Starts with 'cur'. Double 'r' in the middle, and it ends with 'ent'." },
  { zone: 3, word: 'dolphin',
    sentence: 'A friendly dolphin swam beside the reef.',
    hint: "Starts with 'dol'. The 'ph' in the middle makes an 'f' sound." },
  { zone: 3, word: 'shimmer',
    sentence: 'The waves shimmer under the moonlight.',
    hint: "Begins with 'sh'. There is a double 'm' before the 'er' ending." },
  { zone: 3, word: 'seashell',
    sentence: 'Marina Mist collects every seashell she finds.',
    hint: "Two small words joined: 'sea' and 'shell'. Watch for the double 'l'." },
  { zone: 3, word: 'starfish',
    sentence: 'An orange starfish clung to the rock.',
    hint: "Two small words joined: 'star' and 'fish'." },
  { zone: 3, word: 'tidepool',
    sentence: 'Tiny crabs hide in every tidepool.',
    hint: "Two small words joined: 'tide' and 'pool'." },
  { zone: 3, word: 'swimming',
    sentence: 'She spent all morning swimming in the cove.',
    hint: "Starts with 'swim'. Double the 'm' before adding 'ing'." },
  { zone: 3, word: 'floating',
    sentence: 'A piece of driftwood came floating by.',
    hint: "Begins with an 'fl' blend. 'Float' plus 'ing' — the 'oa' says 'oh'." },

  // ══ Zone 4 — Fire: Cinderpath, Ashfall Camp, Magma Forge ═════════════════
  // Band 4 ~grade 3: compound words and -ing/-ed suffix rules.
  { zone: 4, word: 'ember',
    sentence: 'One last ember glowed in the ashes.',
    hint: "Starts with the letter 'e' by itself, then 'mber'." },
  { zone: 4, word: 'flame',
    sentence: 'A blue flame danced above the coals.',
    hint: "Begins with an 'fl' blend. The silent 'e' makes the 'a' say its name." },
  { zone: 4, word: 'spark',
    sentence: 'A single spark landed on the dry grass.',
    hint: "Begins with an 'sp' blend. The middle is 'ar', like in 'park'." },
  { zone: 4, word: 'smoke',
    sentence: 'Grey smoke curled above the camp.',
    hint: "Begins with an 'sm' blend. The silent 'e' makes the 'o' say its name." },
  { zone: 4, word: 'ashes',
    sentence: 'Warm ashes covered the fire pit.',
    hint: "Starts with 'ash', then add 'es' to make it more than one." },
  { zone: 4, word: 'cinder',
    sentence: 'A glowing cinder drifted up from the fire.',
    hint: "Starts with a 'c' that makes an 's' sound. The ending is 'der'." },
  { zone: 4, word: 'desert',
    sentence: 'The desert past Ashfall Camp is blazing hot.',
    hint: "Starts with 'des'. One 's' only, then 'ert'." },
  { zone: 4, word: 'candle',
    sentence: 'She lit one candle inside the tent.',
    hint: "Starts with 'can'. The ending is 'dle', like in 'handle'." },
  { zone: 4, word: 'hottest',
    sentence: 'Magma Forge is the hottest place in the world.',
    hint: "Starts with 'hot'. Double the 't' before adding 'est'." },
  { zone: 4, word: 'flicker',
    sentence: 'The torches flicker along the dark path.',
    hint: "Begins with an 'fl' blend. The 'ck' in the middle comes before 'er'." },
  { zone: 4, word: 'furnace',
    sentence: 'The furnace at Magma Forge never cools.',
    hint: "Starts with 'fur'. It ends with 'ace', where the 'c' sounds like 's'." },
  { zone: 4, word: 'crackle',
    sentence: 'The logs crackle as they burn.',
    hint: "Begins with a 'cr' blend. The 'ck' comes before the 'le' ending." },
  { zone: 4, word: 'lantern',
    sentence: 'She carried a lantern through Ashfall Camp.',
    hint: "Starts with 'lan'. The ending is 'tern' — an 'r' before the 'n'." },
  { zone: 4, word: 'blazing',
    sentence: 'A blazing trail lit up the canyon.',
    hint: "Begins with a 'bl' blend. 'Blaze' drops its silent 'e' before 'ing'." },
  { zone: 4, word: 'chimney',
    sentence: 'Smoke poured out of the stone chimney.',
    hint: "Begins with the 'ch' sound. It ends with 'ney', not 'nee'." },
  { zone: 4, word: 'smolder',
    sentence: 'The coals smolder long after midnight.',
    hint: "Begins with an 'sm' blend. The ending is 'der', like in 'cinder'." },
  { zone: 4, word: 'burning',
    sentence: 'The burning logs kept the camp warm.',
    hint: "Starts with 'burn'. Just add 'ing' — no letters change." },
  { zone: 4, word: 'glowing',
    sentence: 'Her horn was glowing in the dark tunnel.',
    hint: "Begins with a 'gl' blend. 'Glow' plus 'ing' — no letters change." },
  { zone: 4, word: 'volcano',
    sentence: 'The forge was built inside an old volcano.',
    hint: "Three parts: 'vol', 'ca', 'no'. It ends with the letter 'o'." },
  { zone: 4, word: 'campfire',
    sentence: 'They told stories around the campfire.',
    hint: "Two small words joined: 'camp' and 'fire'." },
  { zone: 4, word: 'charcoal',
    sentence: 'Black charcoal covered the fire ring.',
    hint: "Two parts: 'char' and 'coal'. The 'oa' says 'oh'." },
  { zone: 4, word: 'kindling',
    sentence: 'They gathered kindling to start the fire.',
    hint: "Starts with 'kind', like being kind to someone, then add 'ling'." },
  { zone: 4, word: 'scorched',
    sentence: 'The scorched ground still felt warm.',
    hint: "Begins with an 'sc' blend. Ends with 'ched' — the 'ed' sounds like 't'." },
  { zone: 4, word: 'sizzling',
    sentence: 'The hot rocks were sizzling in the rain.',
    hint: "Starts with 'siz'. Double 'z' in the middle, then 'ling'." },
  { zone: 4, word: 'fireplace',
    sentence: 'A stone fireplace warmed the whole hall.',
    hint: "Two small words joined: 'fire' and 'place'." },

  // ══ Zone 5 — Air: Windwhistle Pass, Cloudperch, Galecrest Spire ══════════
  // Band 5 ~grade 3–4: silent letters and common suffixes.
  { zone: 5, word: 'breeze',
    sentence: 'A cool breeze blew across the pass.',
    hint: "Begins with a 'br' blend. Two 'e' letters in the middle, then 'ze'." },
  { zone: 5, word: 'cloudy',
    sentence: 'The sky above Cloudperch is always cloudy.',
    hint: "Starts with 'cloud', then a 'y' that says 'ee'." },
  { zone: 5, word: 'flying',
    sentence: 'She dreamed of flying over the mountains.',
    hint: "Begins with an 'fl' blend. 'Fly' changes its 'y' to 'i' before 'ing'." },
  { zone: 5, word: 'soaring',
    sentence: 'An eagle was soaring above the spire.',
    hint: "Starts with 'soar', where 'oa' says 'or', then add 'ing'." },
  { zone: 5, word: 'gliding',
    sentence: 'She was gliding on the mountain wind.',
    hint: "Begins with a 'gl' blend. 'Glide' drops its silent 'e' before 'ing'." },
  { zone: 5, word: 'updraft',
    sentence: 'A warm updraft lifted her off the cliff.',
    hint: "Two small words joined: 'up' and 'draft'." },
  { zone: 5, word: 'feather',
    sentence: 'A single feather drifted down from the nest.',
    hint: "Starts with 'fea', where 'ea' says 'eh', then 'ther'." },
  { zone: 5, word: 'skyward',
    sentence: 'They climbed skyward toward Galecrest Spire.',
    hint: "Two parts: 'sky' and 'ward'. The 'y' stays a 'y' here." },
  { zone: 5, word: 'whistle',
    sentence: 'The wind makes a low whistle in the pass.',
    hint: "Begins with 'whi'. The 't' is silent, then it ends with 'le'." },
  { zone: 5, word: 'sunrise',
    sentence: 'They reached the summit at sunrise.',
    hint: "Two small words joined: 'sun' and 'rise'." },
  { zone: 5, word: 'thunder',
    sentence: 'Distant thunder rolled across the valley.',
    hint: "Begins with the 'th' sound, then 'under', like the word 'under'." },
  { zone: 5, word: 'rainbow',
    sentence: 'A rainbow appeared after the storm.',
    hint: "Two small words joined: 'rain' and 'bow'." },
  { zone: 5, word: 'highest',
    sentence: 'Galecrest Spire is the highest point around.',
    hint: "Starts with 'high' — the 'gh' is silent — then add 'est'." },
  { zone: 5, word: 'drifting',
    sentence: 'Clouds kept drifting past the high pass.',
    hint: "Begins with a 'dr' blend. 'Drift' plus 'ing' — no letters change." },
  { zone: 5, word: 'mountain',
    sentence: 'The spire rises above the tallest mountain.',
    hint: "Starts with 'moun'. The ending sounds like 'tin' but is spelled 'tain'." },
  { zone: 5, word: 'sunlight',
    sentence: 'Bright sunlight broke through the clouds.',
    hint: "Two small words joined: 'sun' and 'light'. The 'gh' is silent." },
  { zone: 5, word: 'climbing',
    sentence: 'They spent the whole day climbing.',
    hint: "Starts with 'climb' — the 'b' is silent — then add 'ing'." },
  { zone: 5, word: 'windmill',
    sentence: 'An old windmill spun at the edge of the pass.',
    hint: "Two small words joined: 'wind' and 'mill'. Watch the double 'l'." },
  { zone: 5, word: 'lightning',
    sentence: 'Lightning flashed over Galecrest Spire.',
    hint: "Starts with 'light' — the 'gh' is silent — then add 'ning'." },
  { zone: 5, word: 'whirlwind',
    sentence: 'A sudden whirlwind spun the leaves around.',
    hint: "Two small words joined: 'whirl' and 'wind'. Both start with 'w'." },
  { zone: 5, word: 'hurricane',
    sentence: 'The storm grew into a roaring hurricane.',
    hint: "Starts with 'hur'. Double 'r' in the middle, and a silent 'e' at the end." },
  { zone: 5, word: 'whistling',
    sentence: 'The wind was whistling through the pass.',
    hint: "Begins with 'whi'. The 't' is silent, then 'sling'." },
  { zone: 5, word: 'feathered',
    sentence: 'Her feathered wings caught the updraft.',
    hint: "Starts with 'feather', where 'ea' says 'eh', then add 'ed'." },
  { zone: 5, word: 'cloudburst',
    sentence: 'A cloudburst soaked the whole valley.',
    hint: "Two small words joined: 'cloud' and 'burst'." },
  { zone: 5, word: 'breathless',
    sentence: 'The climb left her breathless and happy.',
    hint: "Starts with 'breath' — watch that 'ea' — then add 'less'." },

  // ══ Zone 6 — Spirit: Whisperwood, Moonveil, Starfall Temple ══════════════
  // Band 6 ~grade 4: multisyllable words with -ful/-ness/-ous/-ship endings.
  { zone: 6, word: 'creature',
    sentence: 'No creature in Whisperwood is unfriendly.',
    hint: "Starts with 'crea', where 'ea' says 'ee'. The ending 'ture' sounds like 'cher'." },
  { zone: 6, word: 'treasure',
    sentence: 'The temple holds a hidden treasure.',
    hint: "Starts with 'trea', where 'ea' says 'eh'. It ends with 'sure'." },
  { zone: 6, word: 'twilight',
    sentence: 'They arrived just after twilight.',
    hint: "Starts with 'twi'. The ending 'light' has a silent 'gh'." },
  { zone: 6, word: 'midnight',
    sentence: 'Moonveil glows brightest at midnight.',
    hint: "Two small words joined: 'mid' and 'night'. The 'gh' is silent." },
  { zone: 6, word: 'guardian',
    sentence: 'The last guardian waits inside Starfall Temple.',
    hint: "Starts with 'gu' — that 'u' is silent — then 'ardian'." },
  { zone: 6, word: 'remember',
    sentence: 'She will remember this adventure forever.',
    hint: "Three parts: 're', 'mem', 'ber'. Every vowel in it is an 'e'." },
  { zone: 6, word: 'adventure',
    sentence: 'Her whole adventure led to this temple.',
    hint: "Starts with 'ad'. The ending is 'ture', which sounds like 'cher'." },
  { zone: 6, word: 'enchanted',
    sentence: 'Whisperwood is an enchanted forest.',
    hint: "Starts with 'en'. The middle is 'chant', like a song, then 'ed'." },
  { zone: 6, word: 'moonlight',
    sentence: 'Moonveil is silver in the moonlight.',
    hint: "Two small words joined: 'moon' and 'light'. The 'gh' is silent." },
  { zone: 6, word: 'starlight',
    sentence: 'Starlight pours through the temple roof.',
    hint: "Two small words joined: 'star' and 'light'. The 'gh' is silent." },
  { zone: 6, word: 'beautiful',
    sentence: 'The view from the temple is beautiful.',
    hint: "Starts with 'beau' — three vowels in a row — then 'tiful'." },
  { zone: 6, word: 'wonderful',
    sentence: 'It was a wonderful end to the journey.',
    hint: "Starts with 'wonder', then add 'ful' with just one 'l'." },
  { zone: 6, word: 'important',
    sentence: 'This is the most important battle of all.',
    hint: "Starts with 'im'. The middle is 'port', and it ends with 'ant'." },
  { zone: 6, word: 'different',
    sentence: 'Every pony here looks different.',
    hint: "Starts with 'diff' with a double 'f', then 'erent'." },
  { zone: 6, word: 'butterfly',
    sentence: 'A glowing butterfly landed on her horn.',
    hint: "Two small words joined: 'butter' and 'fly'. Watch the double 't'." },
  { zone: 6, word: 'sparkling',
    sentence: 'The altar was sparkling with light.',
    hint: "Starts with 'spark', then 'ling'. No letters change." },
  { zone: 6, word: 'beginning',
    sentence: 'This is only the beginning of her story.',
    hint: "Starts with 'begin'. Double the 'n' before adding 'ing'." },
  { zone: 6, word: 'happiness',
    sentence: 'Her happiness lit up the whole temple.',
    hint: "Starts with 'happy', but the 'y' changes to 'i' before 'ness'." },
  { zone: 6, word: 'legendary',
    sentence: 'Aurelune is a legendary unicorn.',
    hint: "Starts with 'legend', like a famous story, then add 'ary'." },
  { zone: 6, word: 'mysterious',
    sentence: 'A mysterious voice echoed in the temple.',
    hint: "Starts with 'my' — that 'y' says 'ih'. The ending is 'ous'." },
  { zone: 6, word: 'shimmering',
    sentence: 'A shimmering light circled the altar.',
    hint: "Begins with 'sh'. Double 'm' in the middle, then 'ering'." },
  { zone: 6, word: 'whispering',
    sentence: 'The trees of Whisperwood keep whispering.',
    hint: "Begins with 'whi'. 'Whisper' plus 'ing' — no letters change." },
  { zone: 6, word: 'friendship',
    sentence: 'Their friendship beat the final guardian.',
    hint: "Starts with 'friend' — remember the hidden 'i' — then add 'ship'." },
  { zone: 6, word: 'everything',
    sentence: 'She had everything she needed to win.',
    hint: "Two small words joined: 'every' and 'thing'." },
  { zone: 6, word: 'everlasting',
    sentence: 'Their bond is everlasting.',
    hint: "Two small words joined: 'ever' and 'lasting'." },
]
